/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FrontendUserProfile = IDL.Record({ 'name' : IDL.Text });
export const AnalysisInput = IDL.Record({
  'replyDelay' : IDL.Nat,
  'initiationRatio' : IDL.Nat,
  'toneChange' : IDL.Nat,
  'messageLengthReduction' : IDL.Nat,
  'recentMessage' : IDL.Text,
  'seenIgnoredFrequency' : IDL.Nat,
  'socialMediaActivity' : IDL.Nat,
});
export const AnalysisRecord = IDL.Record({
  'id' : IDL.Text,
  'inputData' : AnalysisInput,
  'sentimentResult' : IDL.Text,
  'riskCategory' : IDL.Text,
  'date' : IDL.Int,
  'score' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'createdAt' : IDL.Int,
  'principalId' : IDL.Text,
  'analysisHistory' : IDL.Vec(AnalysisRecord),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAnalysis' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(FrontendUserProfile)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHistory' : IDL.Func([], [IDL.Vec(AnalysisRecord)], ['query']),
  'getStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalAnalyses' : IDL.Nat,
          'highestScore' : IDL.Nat,
          'averageScore' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUser' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(FrontendUserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([], [IDL.Text], []),
  'saveAnalysis' : IDL.Func([AnalysisRecord], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([FrontendUserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FrontendUserProfile = IDL.Record({ 'name' : IDL.Text });
  const AnalysisInput = IDL.Record({
    'replyDelay' : IDL.Nat,
    'initiationRatio' : IDL.Nat,
    'toneChange' : IDL.Nat,
    'messageLengthReduction' : IDL.Nat,
    'recentMessage' : IDL.Text,
    'seenIgnoredFrequency' : IDL.Nat,
    'socialMediaActivity' : IDL.Nat,
  });
  const AnalysisRecord = IDL.Record({
    'id' : IDL.Text,
    'inputData' : AnalysisInput,
    'sentimentResult' : IDL.Text,
    'riskCategory' : IDL.Text,
    'date' : IDL.Int,
    'score' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'createdAt' : IDL.Int,
    'principalId' : IDL.Text,
    'analysisHistory' : IDL.Vec(AnalysisRecord),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAnalysis' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(FrontendUserProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHistory' : IDL.Func([], [IDL.Vec(AnalysisRecord)], ['query']),
    'getStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalAnalyses' : IDL.Nat,
            'highestScore' : IDL.Nat,
            'averageScore' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUser' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(FrontendUserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([], [IDL.Text], []),
    'saveAnalysis' : IDL.Func([AnalysisRecord], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([FrontendUserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };