/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalysisInput {
  'replyDelay' : bigint,
  'initiationRatio' : bigint,
  'toneChange' : bigint,
  'messageLengthReduction' : bigint,
  'recentMessage' : string,
  'seenIgnoredFrequency' : bigint,
  'socialMediaActivity' : bigint,
}
export interface AnalysisRecord {
  'id' : string,
  'inputData' : AnalysisInput,
  'sentimentResult' : string,
  'riskCategory' : string,
  'date' : bigint,
  'score' : bigint,
}
export interface FrontendUserProfile { 'name' : string }
export interface UserProfile {
  'createdAt' : bigint,
  'principalId' : string,
  'analysisHistory' : Array<AnalysisRecord>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAnalysis' : ActorMethod<[string], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [FrontendUserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHistory' : ActorMethod<[], Array<AnalysisRecord>>,
  'getStats' : ActorMethod<
    [],
    {
      'totalAnalyses' : bigint,
      'highestScore' : bigint,
      'averageScore' : bigint,
    }
  >,
  'getUser' : ActorMethod<[], [] | [UserProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [FrontendUserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[], string>,
  'saveAnalysis' : ActorMethod<[AnalysisRecord], string>,
  'saveCallerUserProfile' : ActorMethod<[FrontendUserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];